<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Data Pelanggan</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }
        h1 {
            text-align: center;
            color: #333;
            margin-bottom: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th {
            background-color: #4a5568;
            color: white;
            padding: 8px;
            text-align: left;
            font-weight: bold;
        }
        td {
            padding: 6px 8px;
            border-bottom: 1px solid #e2e8f0;
        }
        tr:nth-child(even) {
            background-color: #f7fafc;
        }
        .status-aktif {
            color: #38a169;
            font-weight: bold;
        }
        .status-nonaktif {
            color: #e53e3e;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            text-align: right;
            font-size: 10px;
            color: #718096;
        }
    </style>
</head>
<body>
    <h1>Data Pelanggan</h1>
    <p>Total Data di Database: <strong>{{ $totalRecords ?? count($pelanggans) }}</strong></p>
    <p>Data Terexport: <strong>{{ $exportedRecords ?? count($pelanggans) }}</strong></p>
    <p>Tanggal Export: <strong>{{ now()->format('d M Y H:i:s') }}</strong></p>

    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>Nama</th>
                <th>Email</th>
                <th>No. HP</th>
                <th>Kota</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($pelanggans as $index => $pelanggan)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $pelanggan->nama }}</td>
                <td>{{ $pelanggan->email ?? '-' }}</td>
                <td>{{ $pelanggan->no_hp }}</td>
                <td>{{ $pelanggan->kota ?? '-' }}</td>
                <td class="{{ $pelanggan->aktif ? 'status-aktif' : 'status-nonaktif' }}">
                    {{ $pelanggan->aktif ? 'Aktif' : 'Nonaktif' }}
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by Kospin PPOB System
    </div>
</body>
</html>
