<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Data Produk PPOB</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 10px; /* Slightly smaller for more columns */
        }
        h1 {
            text-align: center;
            color: #333;
            margin-bottom: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th {
            background-color: #4a5568;
            color: white;
            padding: 8px;
            text-align: left;
            font-weight: bold;
        }
        td {
            padding: 6px 8px;
            border-bottom: 1px solid #e2e8f0;
        }
        tr:nth-child(even) {
            background-color: #f7fafc;
        }
        .text-right {
            text-align: right;
        }
        .status-aktif {
            color: #38a169;
            font-weight: bold;
        }
        .status-nonaktif {
            color: #e53e3e;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            text-align: right;
            font-size: 10px;
            color: #718096;
        }
    </style>
</head>
<body>
    <h1>Data Produk PPOB</h1>
    <p>Total Data di Database: <strong>{{ $totalRecords ?? count($produks) }}</strong></p>
    <p>Data Terexport: <strong>{{ $exportedRecords ?? count($produks) }}</strong></p>
    <p>Tanggal Export: <strong>{{ now()->format('d M Y H:i:s') }}</strong></p>

    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>Kode</th>
                <th>Nama Produk</th>
                <th>Kategori</th>
                <th class="text-right">HPP</th>
                <th class="text-right">Harga Jual</th>
                <th class="text-right">Profit</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($produks as $index => $produk)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $produk->kode }}</td>
                <td>{{ $produk->nama_produk }}</td>
                <td>{{ $produk->subKategori?->nama ?? '-' }}</td>
                <td class="text-right">{{ number_format($produk->hpp, 0, ',', '.') }}</td>
                <td class="text-right">{{ number_format($produk->harga_jual, 0, ',', '.') }}</td>
                <td class="text-right">{{ number_format($produk->profit, 0, ',', '.') }}</td>
                <td class="{{ $produk->aktif ? 'status-aktif' : 'status-nonaktif' }}">
                    {{ $produk->aktif ? 'Aktif' : 'Nonaktif' }}
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by Kospin PPOB System
    </div>
</body>
</html>
